### PR TITLE
Several small fixes and changes.

### PR DESCRIPTION
**Pull request by EternalModz**
Fixed capitalization, added periods, etc. Just some basic fixes.

### CODE REVIEW

**Comment by refact0r** [comment]
how about fixing something useful instead of capitalization? i hope you realize it was an intentional choice and not a mistake to not capitalize a single word...

**Comment by EternalModz** [comment]
That approach simply looks lazy and unprofessional. It should be obvious that it needs fixing.

**Comment by refact0r** [comment]
you have a furry profile picture.

**Comment by EternalModz** [comment]
So? It's just how I express myself.

**Comment by sudosign** [comment]
text in lowercase makes it more look and feel more "chill" and informal since it lacks proper grammar 

> That approach simply looks lazy and unprofessional. It should be obvious that it needs fixing.

yes its on purpose, makes it feel more clean or aesthetic in a sense

**Comment by zaaahir** [comment]
said unprofessional for a discord theme 😂

**Pull request closed without merging**
