### PR TITLE
nocturne | midnight theme

### PR DESCRIPTION
**Pull request by blackxfiied**
a rounded dark theme with a focus on discord's branding colors, and mobile-inspired design.

image

image

image

mobile for reference:
image

### CODE REVIEW

**Comment by piotr25691** [comment]
correction: you meant [Bunny](https://github.com/pyoncord/Bunny) as Vendetta is defunct.

**Comment by refact0r** [comment]
yeah the name is the only reservation i have about this

**Comment by blackxfiied** [comment]
wait what kind of coincidence is that i just looked up synonym for discord and found the coolest looking one

**Comment by blackxfiied** [comment]
light work

**Comment by bruhmanhehehehehe** [comment]
im gay

**Comment by piotr25691** [comment]
> im gay

this makes no sense

**Comment by blackxfiied** [comment]
@bruhmanhehehehehe trolling died in 2019 bro 💀 kick back and log off

**Comment by piotr25691** [comment]
yes absolutely that was stupid 
 @refact0r can u delete that?

**Comment by blackxfiied** [comment]
no settings icons?

**Comment by refact0r** [comment]
was bugged so i removed it. maybe add back when they fix their shit.

**Pull request merged**
