### PR TITLE
⭕ Added more rounded corners

### PR DESCRIPTION
**Pull request by vorlie**
Added more rounded corners to the theme.

### CODE REVIEW

**Comment by refact0r** [comment]
Thanks for the pr. I've been wanting to do this for a while but never got around to it.

What is `.overlayBackground__86b78 /* Overlay */`?

**Comment by refact0r** [comment]
Nevermind, I figured it out.

**Comment by vorlie** [comment]
Was about to tell you lmao

**Comment by vorlie** [comment]
But yeah I forgot to comment it better sorry for the hassle

**Pull request merged**
