### PR TITLE
Theme 'Channels & Roles'

### PR DESCRIPTION
**Pull request by he3als**
https://user-images.githubusercontent.com/65787561/227799834-1e7bc0d0-b52e-45d7-a974-3738cb57f7ff.mp4

### CODE REVIEW

**Comment by refact0r** [comment]
Is this community server admin only? How do I get to this screen lol

**Comment by he3als** [comment]
Not sure if it's on every server, but it's on most active servers now. Server owners will have to configure it, it's at the top of the channel list:
image

**Comment by refact0r** [comment]
Oh I see

**Comment by refact0r** [comment]
Looks good, thanks.

**Pull request merged**
