### PR TITLE
Update midnight-nord.theme.css

### PR DESCRIPTION
**Pull request by Remco0o**
Make the muted channel/category color look nicer also the unread messages channel color looks better.
More visable diffrences in the colors
new:
Screenshot 2024-03-18 14 56 47
Old:
Screenshot 2024-03-18 14 57 23

### CODE REVIEW

**Comment by refact0r** [comment]
are these based on the official theme?

these colors look a bit off and less bluish than the nord colors. might just be me though.

**Comment by Remco0o** [comment]
I will take a look later today, it isnt based on the nord theme but i will base it on that

**Comment by Remco0o** [comment]
image
Updated the mute channel color, unfortunate the diffrences in the read and unread can be fixed with the nord theme

**Comment by Remco0o** [comment]
A lot better now in the requested nord theme
image

**Pull request merged**
