### PR TITLE
Make favorites icon not the moon icon

### PR DESCRIPTION
**Pull request by lumap**

### CODE REVIEW

**Comment by refact0r** [comment]
how do i enable this favorites thing

**Comment by lumap** [comment]
send <discord://-/channels/@favorites> in a channel and click on it, it's icon will appear below the dm icon

**Comment by lumap** [comment]
actually this might require the `2021-09_favorites_server` experiment to be enabled and you to add a channel/category in the favorites server for the icon to show up.
i'm using `Stable 245033 (8b6a6af) Vencord 96126fa (Standalone)Electron 22.3.26Chromium 108.0.5359.215Host 0.0.283 arm64 OS X 10.15.7 (23.1.0)`

With my patch:


Without my patch:

**Comment by refact0r** [comment]
Doesn't work for me on vesktop. I will merge later once I can verify this is fine.

**Comment by refact0r** [comment]
I have fixed this in 898a02b with a different method. Thanks for pointing it out.

**Comment by refact0r** [comment]
i just realized your way is better lol

**Pull request merged**
